name: Publish Airtable Connect Package to npmjs
on:
  workflow_dispatch:
  # push:
  #   tags:
  #     - "v*"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies
        run: npm ci
      - name: Install jq
        run: sudo apt-get install jq -y
      - name: Release upgrade
        run: |
          VERSION=$(echo ${{ steps.vars.outputs.tag }} | cut -c 2-) && \
          jq '.version |="'$(echo $VERSION)'"' package.json > package.json.tmp && mv package.json.tmp package.json
      - name: Commit release
        uses: EndBug/add-and-commit@v9
        with:
          add: "package.json"
          author_name: "Théo Gillet"
          author_email: "gillettheo1@gmail.com"
          message: "Release ${{ steps.vars.outputs.tag }}"
  build:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies
        run: npm ci
      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
